#!/bin/bash 


cp ~/public_html/cs16/proj0/ourDrawing.gif studentImages/.gif
cp ~acoccia/public_html/cs16/proj0/ourDrawing.gif studentImages/acoccia.gif
cp ~akilpelainen/public_html/cs16/proj0/ourDrawing.gif studentImages/akilpelainen.gif
cp ~aquino/public_html/cs16/proj0/ourDrawing.gif studentImages/aquino.gif
cp ~atse/public_html/cs16/proj0/ourDrawing.gif studentImages/atse.gif
cp ~bmberin/public_html/cs16/proj0/ourDrawing.gif studentImages/bmberin.gif
cp ~bpmccurdy/public_html/cs16/proj0/ourDrawing.gif studentImages/bpmccurdy.gif
cp ~briana_tippets/public_html/cs16/proj0/ourDrawing.gif studentImages/briana_tippets.gif
cp ~Bryanyu/public_html/cs16/proj0/ourDrawing.Gif studentImages/Bryanyu.Gif
cp ~charlottehill/public_html/cs16/proj0/ourDrawing.gif studentImages/charlottehill.gif
cp ~christinenagy/public_html/cs16/proj0/ourDrawing.gif studentImages/christinenagy.gif
cp ~cmoody/public_html/cs16/proj0/ourDrawing.gif studentImages/cmoody.gif
cp ~cquinlan/public_html/cs16/proj0/ourDrawing.gif studentImages/cquinlan.gif
cp ~dani_lai/public_html/cs16/proj0/ourDrawing.gif studentImages/dani_lai.gif
cp ~ddelgado/public_html/cs16/proj0/ourDrawing.gif studentImages/ddelgado.gif
cp ~hamstra/public_html/cs16/proj0/ourDrawing.gif studentImages/hamstra.gif
cp ~ivan/public_html/cs16/proj0/ourDrawing.gif studentImages/ivan.gif
cp ~ivanvuong/public_html/cs16/proj0/ourDrawing.gif studentImages/ivanvuong.gif
cp ~jamesli/public_html/cs16/proj0/ourDrawing.gif studentImages/jamesli.gif
cp ~jamestse/public_html/cs16/proj0/ourDrawing.gif studentImages/jamestse.gif
cp ~j_calderon/public_html/cs16/proj0/ourDrawing.gif studentImages/j_calderon.gif
cp ~jordansmith/public_html/cs16/proj0/ourDrawing.gif studentImages/jordansmith.gif
cp ~jvianna/public_html/cs16/proj0/ourDrawing.gif studentImages/jvianna.gif
cp ~kmorse/public_html/cs16/proj0/ourDrawing.gif studentImages/kmorse.gif
cp ~kyea/public_html/cs16/proj0/ourDrawing.gif studentImages/kyea.gif
cp ~kylejorgensen/public_html/cs16/proj0/ourDrawing.gif studentImages/kylejorgensen.gif
cp ~liu01/public_html/cs16/proj0/ourDrawing.gif studentImages/liu01.gif
cp ~matta/public_html/cs16/proj0/ourDrawing.gif studentImages/matta.gif
cp ~mauricioh/public_html/cs16/proj0/ourDrawing.gif studentImages/mauricioh.gif
cp ~mtsac0924/public_html/cs16/proj0/ourDrawing.gif studentImages/mtsac0924.gif
cp ~njcross/public_html/cs16/proj0/ourDrawing.gif studentImages/njcross.gif
cp ~pbr/public_html/cs16/proj0/ourDrawing.gif studentImages/pbr.gif
cp ~peterhuang/public_html/cs16/proj0/ourDrawing.gif studentImages/peterhuang.gif
cp ~pkoperwas/public_html/cs16/proj0/ourDrawing.gif studentImages/pkoperwas.gif
cp ~sstann/public_html/cs16/proj0/ourDrawing.gif studentImages/sstann.gif
cp ~steven_wright/public_html/cs16/proj0/ourDrawing.gif studentImages/steven_wright.gif
cp ~tongwu/public_html/cs16/proj0/ourDrawing.gif studentImages/tongwu.gif
