CXX = g++
# CXX = clang++

CXXFLAGS = -Wall -Wno-uninitialized

BINARIES=ptrDemo

all: ${BINARIES}

ptrDemo: ptrDemo.o demo1.o demo2.o demo3.o demo4.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $^ -o $@

clean:
	/bin/rm -f ${BINARIES} *.o
