


BINARIES=readFromFile generateNumbers writeToFile readCensusData

CXX= clang++
# CXX= g++

CXXFLAGS= -Wall 

# Some other options:
#   CXXFLAGS= -Wall -Wextra 
#   CXXFLAGS= -Weverything

#	-Wno-c++11-compat-deprecated-writable-strings 
#	-Wno-write-strings

all: $(BINARIES)


clean:
	/bin/rm -f $(BINARIES) *.o
